# Generated by Django 5.2 on 2025-04-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('order_date', models.DateTimeField(verbose_name='주문일시')),
                ('order_status', models.CharField(choices=[('IN_DELIVERY', '배송 중'), ('DELIVERED', '배송 완료'), ('CANCELLED', '취소됨'), ('PENDING', '결제 대기 중'), ('PAID', '결제 완료'), ('REFUNDED', '환불됨')], max_length=20, verbose_name='주문 상태')),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='결제금액')),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='구매자 이름')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='수령자 이름')),
                ('receiver_address', models.CharField(max_length=255, verbose_name='배송지 주소')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='add_attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='부가 속성'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_code',
            field=models.CharField(default='UNDEFINED', max_length=100, verbose_name='카테고리 코드'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='외부 상품코드'),
        ),
        migrations.AddField(
            model_name='product',
            name='option_info',
            field=models.TextField(blank=True, null=True, verbose_name='옵션 정보'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상품 상태'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='상품 설명'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='판매가격'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='재고수량'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='송장번호')),
                ('delivery_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='택배사')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='상품별 주문 ID')),
                ('order_product_name', models.CharField(max_length=200, verbose_name='주문 상품명')),
                ('order_quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image_url', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('sub_image_url', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_info', models.TextField(blank=True, null=True, verbose_name='프로모션 내용')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_info', models.TextField(blank=True, null=True, verbose_name='배송 정보')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.product')),
            ],
        ),
    ]
