# Generated by Django 5.2 on 2025-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_order_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='main_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='product_main_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sub_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='product_additional_images/'),
        ),
    ]
