# Generated by Django 5.2 on 2025-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_vendor_code", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_quantity", models.PositiveIntegerField()),
                ("category_code", models.CharField(blank=True, max_length=50)),
                ("product_description", models.TextField(blank=True)),
                ("product_condition", models.CharField(blank=True, max_length=50)),
                ("extra_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
